### ISSUE TITLE
Casbin core missing its Adapter implementation, so is the casbin-cpp.

### ISSUE THREAD

**Issue by DivyPatel9881** [casbin/casbin-cpp#10]

**Comment by mnprtpsingh** [comment]
Hey @DivyPatel9881 I guess different Adapter's are implemented seperately in different repositories. For examples see [gorm-adapter](https://github.com/casbin/gorm-adapter), [mongodb-adapter](https://github.com/casbin/mongodb-adapter) and [casbin-pg-adapter](https://github.com/casbin/casbin-pg-adapter).
