### ISSUE TITLE
can casbin-cpp support ABAC and eval()？

### ISSUE THREAD

**Issue by carrionbent** [casbin/casbin-cpp#102]
in the casbin docs, I learned that casbin supports abac and the model file is as follows:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_rule, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.sub_rule) && r.obj == p.obj && r.act == p.act
```

can you tell me if casbin-cpp supports abac now？If not support then when will it be ready？ looking forward to your answer, thanks

**Comment by hsluoyz** [comment]
@EmperorYP7 

/cc @xcaptain @divy9881

**Comment by EmperorYP7** [comment]
> can you tell me if casbin-cpp supports abac now？

No, casbin-cpp does **not** support ABAC as of yet.

> If not support then when will it be ready?

I'll be working on this during June and shall be usable by the end of next month at the latest.

**Comment by carrionbent** [comment]
> > can you tell me if casbin-cpp supports abac now？
> 
> No, casbin-cpp does **not** support ABAC as of yet, @carrionbent.
> 
> > If not support then when will it be ready?
> 
> I'll be working on this during June and shall be usable by the end of next month at the latest.

Thank you for your reply, Looking forward to trying this feature sooner

**Comment by carrionbent** [comment]
@EmperorYP7 has the attribute based access control been completed? and does casbin-cpp abac support matchers like eval(p.sub_rule)?

**Comment by EmperorYP7** [comment]
> @EmperorYP7 has the attribute based access control been completed? and does casbin-cpp abac support matchers like eval(p.sub_rule)?

No. It still needs to be implemented. Hopefully, it will be ready by the end of this month.

**Comment by carrionbent** [comment]
> > @EmperorYP7 has the attribute based access control been completed? and does casbin-cpp abac support matchers like eval(p.sub_rule)?
> 
> No. It still needs to be implemented. Hopefully, it will be ready by the end of this month.

@EmperorYP7 , hi, can you tell me if ABAC is already available?

**Comment by EmperorYP7** [comment]
> @EmperorYP7 , hi, can you tell me if ABAC is already available?

No, it isn't. Apologies for the delay. Subscribe to #110 to know whenever it's available.

**Comment by carrionbent** [comment]
> > @EmperorYP7 , hi, can you tell me if ABAC is already available?
> 
> @carrionbent No, it isn't. Apologies for the delay. Subscribe to #110 to know whenever it's available.

ok, thanks for your reply,  looking forward to it.
