### ISSUE TITLE
[QUESTION] Incorrect enforce result when using LoadPolicyLine

### ISSUE THREAD

**Issue by NewbieOrange** [casbin/casbin-cpp#132]
Hi, I was trying casbin-cpp but the behavior is different than the enforcement test on the website editor, if `casbin::LoadPolicyLine()` is used.

The enforcer is constructed with:
```cpp
casbin::Enforcer enforcer{std::shared_ptr<casbin::Model>(
        casbin::Model::NewModelFromString(GetFileConfigFromCloud("model.conf")))};
```

The model is RBAC with resource roles (exactly copied from the website), and the policy is:

```
p, data_group_admin, data_group, read

g, me, data_group_admin
g2, route, data_group
```

However, enforce("me", "route", "read") always return false, while the website shows it should be true.

If I add the following line to the policy file, then it does return true, proving the policy is somewhat (partially?) loaded:
```
p, me, route, read
```

The policy is loaded using `casbin::LoadPolicyLine()`:

```cpp
const std::string policy = GetFileConfigFromCloud("policy.csv");
for (const auto& line : SplitStringView(policy, "\n")) {
    std::string line_str = std::string(line);
    casbin::LoadPolicyLine(casbin::Trim(line_str), enforcer.GetModel().get());
}
```

If the policy is loaded by simply passing the path to the `Enforcer` constructor, everything works as expected.

Any thoughts about what is wrong with my code?

**Comment by NewbieOrange** [comment]
I managed to workaround this by creating a "StringAdapter". Not sure what is going on.

**Comment by hsluoyz** [comment]
@EmperorYP7

**Comment by noob20000405** [comment]
@NewbieOrange Hi, I think it might be because you didn't use method ```BuildRoleLinks()```. Try to call 
```enforcer.BuildRoleLinks()```
after the loop of loading lines to see if it works.

**Comment by hsluoyz** [comment]
Closed as resolved.
