### ISSUE TITLE
window.h in ubuntu gives error.

### ISSUE THREAD

**Issue by NitinBhasneria** [casbin/casbin-cpp#14]

**Comment by romitkarmakar** [comment]
Working on this repo will require you to have visual studio installation in windows, with workload for c++ installed.

**Comment by NitinBhasneria** [comment]
Do you mean I cant work on this repo in ubhntu?

**Comment by NitinBhasneria** [comment]
@techoner can you review this ?

**Comment by PsiACE** [comment]
> You can add makefile to make the current enforcer code compile. Use macro to disable some Windows-specify things.

See https://github.com/casbin/casbin-cpp/pull/6#issuecomment-595792065
