### ISSUE TITLE
Refact ABACData by a Json Parser.

### ISSUE THREAD

**Issue by sheny1xuan** [casbin/casbin-cpp#165]
### Description
+ I noticed current `ABACData` maybe only support [one level](https://github.com/casbin/casbin-cpp/blob/abaa2174f0a4c6df2a25c21c388c15939f472655/casbin/enforcer.cpp#L481) depth json (e.g. `a.b`). If we want to makes more level, we need build `ABACData` tree to support. I think maybe we need a json lib to make things easier.
+ [nlohmann/json](https://github.com/nlohmann/json) is a json parser used modern cpp and it is easy to use. I want to use this lib to construct duktape object. In this way, we can use json to build duktape object by recursion. Then we can make evaluate `a.b.c` possible.
+ And when we need to eavl the [abac policy](https://github.com/casbin/casbin-cpp/blob/abaa2174f0a4c6df2a25c21c388c15939f472655/casbin/enforcer.cpp#L95) ,  we can easily update corresponding object int this way.
+ Following is the `pseudo code`. Because I am not familiar with the casbin-cpp, and the idea maybe worry, so I need some advices. And if it make sense, I will try it.
+ Thanks for your help !!

``` cpp
void MakeObjectFromJson(json& j) {
    if (j.is_null()) {
        return;
    }

    for (auto& cur_j: j.items()) {
        if (cur_j.value().is_object()) {
            MakeObjectFromJson(cur_j.value()); 
            duktapeAddPropObj();
        } else if (cur_j.value().is_number_float()) {
            duktapeAddFloat();
        } else if (cur_j.value().is_number_integer()) {
            duktapeAddInterger();
        } else if (cur_j.value().is_string()) {
            duktapeAddString();
        } else {
            return;
        }
    }
}
```

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin-cpp/pull/172
