### ISSUE TITLE
Included nlohmann::json interfere with project dependencies

### ISSUE THREAD

**Issue by NewbieOrange** [casbin/casbin-cpp#168]
### Description

The recently added `nlohmann::json` has an older version than my project's minimal requirement, and casuing it failed to build.

Can we include a customized version of the `json.hpp` (adding `casbin` namespace?) to avoid interferences?

**Comment by sheny1xuan** [comment]
Of course, we can include a customized version of the `json.hpp`, adding it to casbin namespace to avoid different version of the `json` lib.
Maybe we should update the version of `nlohmann::json` at the same time. What's version should be better? `3.9` or `3.10`?

**Comment by NewbieOrange** [comment]
Newer is better, probably :)
