### ISSUE TITLE
[PyCasbin-on-CPP] replace some PyCasbin code with Casbin-CPP to improve PyCasbin's performance

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-cpp#173]
See: https://github.com/casbin/pycasbin/issues/225

**Comment by hsluoyz** [comment]
@Abingcbc will work on the PyCasbin part.

@sheny1xuan will work on the Casbin-CPP part.

Please work together.

**Comment by EmperorYP7** [comment]
This is going to be interesting!

**Comment by hsluoyz** [comment]
@EmperorYP7 I think a standalone lib on pip is also great! Users will not face any breaking change with our version upgrade then. We need to make sure the API between pip's casbin and pycasbin-on-cpp are the same.

**Comment by ZhengLin-Li** [comment]
As https://github.com/casbin/casbin-cpp/issues/174 has fixed this issue, could we close it to avoid confusion?
