### ISSUE TITLE
[PyCasbin] Make the library pip installable

### ISSUE THREAD

**Issue by EmperorYP7** [casbin/casbin-cpp#174]
From: https://github.com/casbin/casbin-cpp/issues/173

### Description

The current `pycabsin` target (library) can only be installed by [compiling and installing locally](https://github.com/casbin/casbin-cpp/tree/master/bindings#installing-the-pycasbin-module). People use Python for its utility, so we must make it simpler for the clients to install and use pycasbin (on cpp) with superior performance.

For reference, have a look at [tensorflow](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python).

**Comment by hsluoyz** [comment]
@sheny1xuan plz work on it.

**Comment by sheny1xuan** [comment]
> @sheny1xuan plz work on it.

I will do it.
