### ISSUE TITLE
[doc] Benchmark data about casbin-cpp in `casbin.org` maybe wrong.

### ISSUE THREAD

**Issue by sheny1xuan** [casbin/casbin-cpp#176]
### Description
+ `casbin-cpp` benchmark data in [official website](https://casbin.org/docs/en/benchmark) maybe wrong, `RBAC` time comlexity maybe `O(n)` rather than `O(1)`, n is policy numbers in memory. So with data increase in `RBAC small`, `RBAC medium` and `RBAC large`, consumed time will increase. We can ref to this [action](https://github.com/casbin/casbin-cpp/runs/4070980022?check_suite_focus=true), and other languge benchmark.
![image](https://user-images.githubusercontent.com/43725202/145145731-e287f28c-7dc2-4ba0-bae7-6221aefe65f5.png)
+ And when I run `Large benchmark` in my local machine, I can't get the benchmark result, even I have run it at least one hour. I only get the some small data case benchmark result.
![image](https://user-images.githubusercontent.com/43725202/145146265-2fc21f80-6223-4a68-a391-b05d13d40354.png)

**Comment by hsluoyz** [comment]
@sheny1xuan good finding! Can you fix the bencnmark number in the docs?

**Comment by sheny1xuan** [comment]
> @sheny1xuan good finding! Can you fix the bencnmark number in the docs?

Of course, but these are something wrong when I run `large rbac model`. We I fix it, I will update the newest benchmark number in the docs.

**Comment by hsluoyz** [comment]
@EmperorYP7 any comments?

**Comment by EmperorYP7** [comment]
So here are the benchmark results when I fed it in casbin.org


![](https://user-images.githubusercontent.com/62606998/130142096-ccff8e5d-b963-4035-b7df-00ad52ad977d.png)

**Comment by sheny1xuan** [comment]
> So here are the benchmark results when I fed it in casbin.org
> 
> ![](https://user-images.githubusercontent.com/62606998/130142096-ccff8e5d-b963-4035-b7df-00ad52ad977d.png)

Maybe in this benchmark reuslt, `rbac small` should be `50985511 / 78 = 653660.40ns` and `rbac medium` should be `906444271 / 10 = 90644427.1ns`. Is my calculation correct？

**Comment by EmperorYP7** [comment]
> Maybe in this benchmark reuslt, `rbac small` should be `50985511 / 78 = 653660.40ns` and `rbac medium` should be `906444271 / 10 = 90644427.1ns`. Is my calculation correct？

1. The `CPU` and `Time` already show runtime/operation. You don't need to calculate it.
2. I took the `CachedRBAC` workflow for the benchmark.

**Comment by hsluoyz** [comment]
@sheny1xuan sounds good

**Comment by sheny1xuan** [comment]
> So here are the benchmark results when I fed it in casbin.org
> 
> ![](https://user-images.githubusercontent.com/62606998/130142096-ccff8e5d-b963-4035-b7df-00ad52ad977d.png)

Hi, when I update the result above, I found `casbin-cpp' performance` maybe not good as we expect. It's too slow compared to `golang` and `rust`. I think maybe the result is outdated for us, and I rerun the benchmark in my local mahcine. Here is the runtime result, and it's faster than before, but I think it's not enough compared to `golang` and `rust`. And I change somewhere in `rbac manager` to improve the casbin-cpp performance, you can find changes in this [commit].(https://github.com/sheny1xuan/casbin-cpp/commit/fabef3344e8b694121c93b0e0392e05c3eafd3c7)

![image](https://user-images.githubusercontent.com/43725202/145511008-ae0e56f3-c35c-416c-a5c3-b351acf2e40b.png)

Maybe we should some profiling for casbin-cpp to deal with it's performance problem as @hsluoyz say. Then we can update the docs latter. @EmperorYP7

**Comment by EmperorYP7** [comment]
> Maybe we should do some profiling for casbin-cpp to deal with it's performance problem as @hsluoyz say. Then we can update the docs latter. @EmperorYP7

This is exactly what I was up to a few months ago. I tried to set up [visual profiling for casbin-cpp](https://github.com/EmperorYP7/casbin-cpp/tree/visual-benchmark). However, I couldn't find a way to include it in the existing CI workflows.

**Comment by hsluoyz** [comment]
@EmperorYP7 currently Casbin-CPP is even slower than Go Casbin or jCasbin. This is not common sense because we know C++ will usually be at least 10x faster than Go or Java. We need at least a manual profiling approach to troubleshoot the slow part in our Casbin C++ code. Integrating the profiling into CI is not required. For now we can just provide a manual profiling way to make sure the performance downgrade troubleshooting is not blocked.

**Comment by EmperorYP7** [comment]
> This is not common sense because we know C++ will usually be at least 10x faster than Go or Java.

Even I expected it to be a lot faster. We need to look into what is causing the bottleneck. (as far as I can recall, it was related to duktape)

> For now we can just provide a manual profiling way to make sure the performance downgrade troubleshooting is not blocked.

Alright, making a new issue for profiling.

**Comment by EmperorYP7** [comment]
We can update the benchmarks on the websites now

**Comment by hsluoyz** [comment]
@sheny1xuan

**Comment by sheny1xuan** [comment]
I have udpated the latest benchmark data.
