### ISSUE TITLE
how to finish AddNamedDomainMatchingFunc' function in  using casbin-cpp, 

### ISSUE THREAD

**Issue by yuzhishuo** [casbin/casbin-cpp#179]
like this :

![image](https://user-images.githubusercontent.com/19743727/147639790-42a3ebbe-7933-4897-9ea0-f46094b82a02.png)

**Comment by hsluoyz** [comment]
@sheny1xuan

**Comment by sheny1xuan** [comment]
Hi, I think you want to use `RBACModelWithPattern`, you can refer to this [test case](https://github.com/casbin/casbin-cpp/blob/e9628f394e7b3688e28fc759a879014bf745c2a0/tests/model_enforcer_test.cpp#L474) to register the match function for your rbac model.

**Comment by hsluoyz** [comment]
> But there are't a interface AddNamedDomainMatchingFunc for Enforcer in casbin-cpp.

@sheny1xuan does Golang have it? Can we add it here too?

**Comment by yuzhishuo** [comment]
> Hi, I think you want to use `RBACModelWithPattern`, you can refer to this [test case](https://github.com/casbin/casbin-cpp/blob/e9628f394e7b3688e28fc759a879014bf745c2a0/tests/model_enforcer_test.cpp#L474) to register the match function for your rbac model.
> 
> But there are't a interface `AddNamedDomainMatchingFunc` for `Enforcer` in casbin-cpp. You should get the `RoleManager` of the `Enforcer`, then you can `AddMatchingFunc` for this `RoleManager`.
> 
> > ```c++
> >    casbin::Enforcer e(rbac_with_pattern_model_path, rbac_with_pattern_policy_path);
> >   casbin::DefaultRoleManager* rm_tmp = dynamic_cast<casbin::DefaultRoleManager*>(e.rm.get());
> >    rm_tmp->AddMatchingFunc(casbin::KeyMatch2);
> > ```
👌

**Comment by sheny1xuan** [comment]
> > But there are't a interface AddNamedDomainMatchingFunc for Enforcer in casbin-cpp.
> 
> @sheny1xuan does Golang have it? Can we add it here too?

Yes, golang have this interface, I will add it in latter commit.
