### ISSUE TITLE
Passing policy to Adapter as a sting buffer instead of a text filepath

### ISSUE THREAD

**Issue by MaximAxelrodFirebolt** [casbin/casbin-cpp#200]
### Description
We want to change the current way of passing policy to casbin's Adapter. The current way is to pass filepath of policy.csv file to Enforcer constructor. We want to change this in a such way, that Enforcer's constructor will accept string buffer which contains policy instead of policy filepath. 

i.e. to add the following constructor `Enforcer(const std::string& model_path, const std::string &policy)`

What is the best way to do so? 

Is it a good idea in general? Our policy is limited in size of hundred KB.

**Comment by hsluoyz** [comment]
@MaximAxelrodFirebolt I think you need a String Adapter like this one: https://casbin.org/docs/en/adapters#:~:text=For%20JSON-,String%20Adapter,-String ?

We usually implement such an adapter in a separated repo. Do you want to contribute the code?

**Comment by MaximAxelrodFirebolt** [comment]
if we succeed to implement, of course, we will contribute!

**Comment by MaximAxelrodFirebolt** [comment]
@hsluoyz [hsluoyz](https://github.com/hsluoyz) yes, exactly, I need like this but for C++, will try to implement it

**Comment by hsluoyz** [comment]
@MaximAxelrodFirebolt plz implement it in this repo, because importing lib in C++ is not very easy

**Comment by hsluoyz** [comment]
@cs1137195420
