### ISSUE TITLE
Why enforcer has two herader files (casbin_enforcer.h and enforcer.h) ? 

### ISSUE THREAD

**Issue by MaximAxelrodFirebolt** [casbin/casbin-cpp#201]
Hi All,

I need to add a new constructor to the existing enforcer, 
`Enforcer(const std::string& model_path, std::stringstream && policy)`, and I see that I must add the CTOR declaration in 2 files, 

casbin/include/casbin/casbin_enforcer.h
and 
contrib/casbin/casbin/enforcer.h

If I add the CTOR declaration only into one of them, compilation fails. So I just don't understand why casbin has two headers for enforcer?

What is the correct way to add a new constructor to enforcer?

**Comment by sheny1xuan** [comment]
Hi, current code only have one header file of [enforcer](https://github.com/casbin/casbin-cpp/blob/master/include/casbin/enforcer.h). I think you should update your branch to the [ latest version](5d9e56cb97ca456158f94c614af1dbfba2e7a3fc).
