### ISSUE TITLE
Cmake instructions out of date for newer versions including nlohmann_json

### ISSUE THREAD

**Issue by drteeth** [casbin/casbin-cpp#203]
### Description

I'm trying to include casbin-cpp in an android project. This worked great for version 1.37.x by following the `FetchContent` directions for CMake in the readme. I now need to use the newer features of casbin and tried to upgrade to 1.50.1. This fails as there is now a dependency on `nlohmann_json`:

```
CMake Error at *snip* _deps/casbin-src/casbin/CMakeLists.txt:73 (add_library):
  Target "casbin" links to target "nlohmann_json::nlohmann_json" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?  
```

I'm wondering if someone at casbin could update the readme with instructions for newer versions of casbin-cpp. I'm happy to do any leg work, but I'm inexperienced in both C++ and CMake, so that may not be of much use.

As a first step, I'd like to know if this is a problem that should be solved in my app/lib as the consumer of casbin's CMake, or should this be solved within casbin-cpp. 

Here is a reasonable facsimile of my CMakeLists.txt:

```cmake
cmake_minimum_required(VERSION 3.22.1)

project(
        "cmakesample"
        VERSION 1.0
        DESCRIPTION "Demo project including casbin"
        LANGUAGES CXX C
)

set(CMAKE_CXX_STANDARD 17)

set(CMAKE_MODULE_PATH
        ${CMAKE_MODULE_PATH}
        ${CMAKE_SOURCE_DIR}/modules
        )

include(FindExtPackages)

add_library(
        cmakesample
        SHARED
        native-lib.cpp)

target_link_libraries(
        cmakesample
        casbin
)

set(cmakesample_INCLUDE_DIR ${casbin_SOURCE_DIR}/include)
target_include_directories(cmakesample PRIVATE ${cmakesample_INCLUDE_DIR})
```

Thanks for your time

**Comment by hsluoyz** [comment]
@EmperorYP7 can you help resolve this case?

**Comment by EmperorYP7** [comment]
@hsluoyz Its fixed now

**Comment by hsluoyz** [comment]
@EmperorYP7 thanks! I saw it: https://github.com/EmperorYP7/casbin-CMake-setup/commit/af30c1058ca421a6df8a0ed7c4057febb68dc9bd

BTW, can we move this repo: https://github.com/EmperorYP7/casbin-CMake-setup to the org https://github.com/casbin-cpp to serve as better showcase?

**Comment by EmperorYP7** [comment]
Sure!

**Comment by EmperorYP7** [comment]
We also need to update license and copyright info in the source files if we're including it in casbin-cpp org

**Comment by hsluoyz** [comment]
@EmperorYP7 thanks! Issue created here: https://github.com/casbin-cpp/casbin-CMake-setup/issues/3

**Comment by drteeth** [comment]
Thanks you @EmperorYP7 I really appreciate that!
