### ISSUE TITLE
set_target_properties called with incorrect number of arguments

### ISSUE THREAD

**Issue by cs1137195420** [casbin/casbin-cpp#205]
### Description
This error occurred when I tried to run a CMake project including casbin-cpp on Visual Studio2019. It seems that set_target_properties didn't recognize it after PREFIX was set to empty character, which caused incorrect number of arguments. Is this a bug that needs to be fixed?

### My System Info
Windows 10, cmake version 3.24.0-rc2

### Screenshots
The CMakeLists.txt of project:
![image](https://user-images.githubusercontent.com/46164668/177794022-612dafed-d5bd-4ac2-808e-1d4773254884.png)

The error message:
![image](https://user-images.githubusercontent.com/46164668/177793287-6c673da7-dcaa-48c9-821d-200c92ad2dd0.png)

The place where the error occurred:
![image](https://user-images.githubusercontent.com/46164668/177793649-b0d57460-f9e5-4faa-af57-39cbb3b74dc2.png)

**Comment by hsluoyz** [comment]
@sheny1xuan

**Comment by sheny1xuan** [comment]
Of course, casbin-cpp support three platform, you can try to fix it.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin-cpp/pull/237
