### ISSUE TITLE
[Question] no test for ABAC

### ISSUE THREAD

**Issue by JalinWang** [casbin/casbin-cpp#208]
I'm wondering why there is no test for ABAC. 
There used to be some test cases, but they are gone after `duktape evaluator` is removed in https://github.com/casbin/casbin-cpp/pull/196

Searching result: https://github.com/casbin/casbin-cpp/search?l=C%2B%2B&q=ABAC

**Comment by hsluoyz** [comment]
Hi @sheny1xuan any reasons for removing the ABAC tests?

/cc @EmperorYP7 @cs1137195420

**Comment by sheny1xuan** [comment]
@JalinWang  Yes, `exprtk evaluator` don't support `ABAC`. `duktape evaluator` didn't support `total ABAC`, we use `json` for input rather than reflection. `std` library don't support reflection, we need to think of new ways to support `ABAC`.

**Comment by JalinWang** [comment]
> @JalinWang Yes, `exprtk evaluator` don't support `ABAC`. `duktape evaluator` didn't support `total ABAC`, we use `json` for input rather than reflection. `std` library don't support reflection, we need to think of new ways to support `ABAC`.

@sheny1xuan  uhh it sounds like a breaking change. I think it would be better to add a note somewhere, e.g., https://casbin.io/docs/overview#feature-set-for-different-languages, as well as a description in PR https://github.com/casbin/casbin-cpp/pull/196 for tracking. It has taken me some time to reason about what happened with  https://github.com/casbin/casbin-cpp/pull/170 https://github.com/casbin/casbin-cpp/pull/189#issuecomment-1066779734  https://github.com/casbin/casbin-cpp/pull/196/

**Comment by hsluoyz** [comment]
@sheny1xuan so we are losing some features after the change? Which features are still missing? Can we create some issues to track these missing ones?
