### ISSUE TITLE
how to persist polices with PostgreSQL

### ISSUE THREAD

**Issue by jackleibest** [casbin/casbin-cpp#213]
Seems the casbin could be save the policies to the PostgreSQL via Go lang or Java, however, how to do it with C++? Are the any adapters?

**Comment by hsluoyz** [comment]
@cs1137195420

**Comment by cs1137195420** [comment]
@jackleibest The PostgreSQL adapter is not implemented yet, we will implement it later and put it in a separate repository named [postgresql-adapter](https://github.com/casbin-cpp/postgresql-adapter).

**Comment by hsluoyz** [comment]
@cs1137195420 we should make an ORM adapter first, see: https://github.com/casbin/casbin-cpp/issues/214

@jackleibest do you have any suggestions for a C/C++ ORM?

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casbin/casbin-cpp/issues/239
