### ISSUE TITLE
Multithreaded usage of casbin

### ISSUE THREAD

**Issue by AlekseiChFirebolt** [casbin/casbin-cpp#226]
Hey Guys. 
I have an issues to use casbin in multithreaded mode in C++, it might be great if you will help me to way out :)
If someone can please share - do you have a plans to support mutlithreading? 

Context:
- need to call "IEnforcer::enforce" method multiple times from several threads
- policy and model defined on creation of IEnforcer instance
- Flaky "segmentation fault" take a place in this special call

Problems:
- Enforcer class not implemented for ThreadSafe usage ( Enforce method not a const and have no mutex )
- SyncedEnforcer class not implemented for ThreadSafe usage of ::Enforce method ( using of shared_mutex and read protecting shared_lock will not prevent second thread from using "m_enforce", which will mutate "FunctionMap m_func_map" and other properties of Enforcer internal state in undefined order).

Quesions:
- is anyone can to work on issue like this?
- do you guys have any plans to improve multithreading in c++ libraray? 

Best regards, Aleksei

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by PokIsemaine** [comment]
Thanks for feedback. 
You are right. It looks like there is something wrong with the current implementation of `SyncedEnforcer::Enforce` and our associated tests are flawed.
I plan to fix this and add some tests in the next few days.
