### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by fishsclue** [casbin/casbin-cpp#241]
There is a memory leak when I call this function in a loop, how can I fix this 

bool vBasePermissionsImpl::Enforce(const QVector<QString>& params)
{
    std::vector<std::variant<std::string, std::shared_ptr<nlohmann::json>>> dataVector;

   
    CleanDataVector(dataVector);

    for(const auto& qStr : params)
    {
        std::string str = qStr.toStdString();
        try
        {
            QJsonDocument jsonDoc = QJsonDocument::fromJson(qStr.toUtf8());
            if(!jsonDoc.isNull() && jsonDoc.isObject())
            {
                auto jsonPtr = std::make_shared<nlohmann::json>(nlohmann::json::parse(jsonDoc.toJson().toStdString()));
                dataVector.push_back(jsonPtr);
            }
            else
            {
                dataVector.push_back(str);
            }
        }
        catch (const std::exception&)
        {
            dataVector.push_back(str);
        }
    }

    bool result = e.Enforce(dataVector);

    
    CleanDataVector(dataVector);

    return result;
}

void CleanDataVector(std::vector<std::variant<std::string, std::shared_ptr<nlohmann::json>>>& dataVector)
{
    for(auto& item : dataVector)
    {
        if(std::holds_alternative<std::shared_ptr<nlohmann::json>>(item))
        {
            auto jsonPtr = std::get<std::shared_ptr<nlohmann::json>>(item);
            jsonPtr.reset();
        }
    }

    
    dataVector.clear();
}

**Comment by hsluoyz** [comment]
Dup with: https://github.com/casbin/casbin-cpp/issues/243
