### ISSUE TITLE
Add Azure Pipelines CI badge

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-cpp#26]
We can add Azure Pipelines as our CI, so all the code can be built and tested automatically on Windows.

![image](https://user-images.githubusercontent.com/3787410/84586227-32b8b480-ae4a-11ea-8dbb-f34f82706f4e.png)

See how we setup Azure Pipelines CI for Casbin.NET as an example if needed: https://github.com/casbin/Casbin.NET/issues/32#issuecomment-642580444

**Comment by hsluoyz** [comment]
@divy9881 can anyone work on it?

**Comment by divy9881** [comment]
Yes, I can set up the CI, but actually, I will be needing casbin Azure DevOps credentials.

**Comment by hsluoyz** [comment]
@divy9881 OK. We can start this task now. Let me know if you need any cred/key in Azure DevOps.

**Comment by KaranaLJX** [comment]
> @divy9881 can anyone work on it?

I want to try it , but i can not register an Azure account

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin-cpp/issues/35
