### ISSUE TITLE
Fix Casbin-CPP image

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-cpp#27]
![image](https://user-images.githubusercontent.com/3787410/84586825-15d1b080-ae4d-11ea-8b1b-954e5e24cc85.png)

@divy9881 The "+" char in URL: https://casbin.org/img/langs/c++.png is not correctly handled. Please rename the file from c++.png to cpp.png in both casbin-website and this repo's README.

**Comment by divy9881** [comment]
Actually, the image has not been hosted yet, that's the problem, the image works fine on my localhost, localhost:3000/img/langs/c++.png. I have checked it on casbin.github.io, there is no image.

**Comment by divy9881** [comment]
![Screenshot (158)](https://user-images.githubusercontent.com/39230975/84587015-4a3b7180-ae39-11ea-938c-01996843475c.png)

**Comment by hsluoyz** [comment]
Maybe that image is not deployed because it's not referenced in the website, can you also add it to: https://casbin.org/docs/en/overview ?

**Comment by divy9881** [comment]
Now the image has taken the full width : )))

**Comment by hsluoyz** [comment]
Please fix it to same width as other icons.

**Comment by hsluoyz** [comment]
@divy9881 any progress? Because the current look is kind of ugly in the website..
