### ISSUE TITLE
Investigate if there's a suitable C/C++ expression evaluator

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-cpp#3]
Casbin uses expression evaluator to evaluate matchers. If there's no such thing, Casbin C/C++ cannot be done.

**Comment by DivyPatel9881** [comment]
Yeah, you are absolutely right, I had gone through this while passing through docs, and found a solution regarding this...
Just check this out [cparse](https://github.com/cparse/cparse)

**Comment by xcaptain** [comment]
I would recommend http://chaiscript.com/ looks like another option

**Comment by DivyPatel9881** [comment]
Yeah, definitely, it can be considered.

**Comment by DivyPatel9881** [comment]
@hsluoyz which expression evaluator should be used for the implementation? Please let me know, as I am going for enforcer which requires them as their dependency.

**Comment by DivyPatel9881** [comment]
So should I go with [cparse](https://github.com/cparse/cparse).

**Comment by xcaptain** [comment]
@DivyPatel9881 you are working really fast, I think you can choose whatever you like as long as we have a basic working version.

**Comment by DivyPatel9881** [comment]
Thanks, @xcaptain, I just wanted to be sure. No problem will go with cparse, found promising.

**Comment by DivyPatel9881** [comment]
Currently, I am implementing enforcer, and I am in need of expression evaluator after a lot of research I found a very good and very satisfying library for casbin-CPP [duktape](https://duktape.org/).
The cparse does not support object arguments and with chaiscript, I am facing build issues. Currently, duktape is satisfying all the needs of expression evaluator

**Comment by romitkarmakar** [comment]
I think we can go with [muParser](https://beltoforion.de/article.php?a=muparser). It has a similar API with the govaluate package.

**Comment by DivyPatel9881** [comment]
muParser only supports ```double``` as variable type and only supports certain types of functions as can be seen here : [muparser](https://beltoforion.de/article.php?a=muparser&p=defining_functions), it is specifically used for Math evaluation will not serve well to the Casbin's usecase.

**Comment by romitkarmakar** [comment]
@DivyPatel9881 you are right..

**Comment by hsluoyz** [comment]
@divy9881 what's the evaluator used eventually in Casbin-CPP?

**Comment by divy9881** [comment]
https://duktape.org/index.html
Duktape is a very light and very generic expression evaluator for C++ out there. As you know, we have been facing bottle-neck due to this functionality in other libraries like Casbin-Rust.

**Comment by hsluoyz** [comment]
OK. So its source code is already embedded inside our own repo.

When we finish adding benchmark test cases like how we did in Go, Rust. We can evaluate duktape's performance compared to other languages, and maybe tune it if neccessary.

**Comment by hsluoyz** [comment]
Finally we go with duktape: https://github.com/casbin/casbin-cpp/blob/master/casbin/duktape/duktape.cpp
