### ISSUE TITLE
Add casbin-cpp to opencollective.

### ISSUE THREAD

**Issue by divy9881** [casbin/casbin-cpp#34]
I have added the link to open-collective for casbin-cpp under readme to show the contributors. @hsluoyz can you add casbin-cpp to open-collective.

**Comment by hsluoyz** [comment]
Created: https://opencollective.com/casbin-cpp

Still need to wait some time for the image to be available.

**Comment by hsluoyz** [comment]
https://github.com/casbin/casbin-cpp#contributors

**Comment by hsluoyz** [comment]
Adding to open-collective requires this repo to have 100 stars: https://opencollective.com/create/opensource

![image](https://user-images.githubusercontent.com/3787410/84868702-b0c9c500-b0af-11ea-8858-3d837dd77a31.png)

@divy9881 please advertise casbin-cpp !

**Comment by hsluoyz** [comment]
Added now as we already got 100+ stars: https://opencollective.com/casbin-cpp
