### ISSUE TITLE
Add Microsoft azure pipeline badge.

### ISSUE THREAD

**Issue by divy9881** [casbin/casbin-cpp#35]
@hsluoyz can you add the azure pipeline badge to the readme.

**Comment by hsluoyz** [comment]
I saw you added the badge.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin-cpp/commit/cadcae6b44aa0068465d03bb721325c56c8188f0

**Comment by divy9881** [comment]
I think the link must be https://dev.azure.com/Casbin/casbin/_build?definitionId=2&branchName=master

**Comment by hsluoyz** [comment]
@divy9881 fixed in: https://github.com/casbin/casbin-cpp/commit/9a3a86a27941f4bec2380beb95982d507d7f5e92
