### ISSUE TITLE
Setup some PR actions.

### ISSUE THREAD

**Issue by divy9881** [casbin/casbin-cpp#36]
Some PR actions like Semantic-PR, coveralls(for code coverage) and probably travis-CI after we add CMake support for cpp.

**Comment by divy9881** [comment]
I don't have the authority to add this actions, so either you will have to give me access or you can add it.

**Comment by hsluoyz** [comment]
I have added you:

![image](https://user-images.githubusercontent.com/3787410/84842631-35005600-b078-11ea-94af-ab1834ac3e6b.png)

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin-cpp/pull/63
