### ISSUE TITLE
Add synced and cached enforcer

### ISSUE THREAD

**Issue by divy9881** [casbin/casbin-cpp#38]
This are the links to the enforcers implemented in golang for casbin-core. We need to port this code to casbin-cpp to extend the feature of enforcement.
https://github.com/casbin/casbin/blob/master/enforcer_cached.go
https://github.com/casbin/casbin/blob/master/enforcer_synced.go

**Comment by hsluoyz** [comment]
This one is definitely needed.

**Comment by zintown** [comment]
let's do it~

**Comment by divy9881** [comment]
You can refer to the above links from casbin golang repository.

**Comment by divy9881** [comment]
What's the status of this issue, @zintown?

**Comment by zintown** [comment]
I am trying to learn go and review c++, and read the source code.

**Comment by zintown** [comment]
I have lots of homworks to do, and it 's near deadline these days, so my progress is slow. But don't worry, I'll keep up with that issue
@divy9881

**Comment by bokket** [comment]
I try to analyze the difference between c++ and golang in synced performance from some aspects.C++ <<atomic>> library and <<mutex>> library can satisfy asynchronous requests.But I found difference through the realization of https://github.com/casbin/casbin/blob/master/enforcer_synced.go.C++ has no standard library for timer operations.This means that a timing operation should be implemented through the <<chrono>> library.I need some suggestions and directions.

**Comment by bokket** [comment]
I try to analyze the difference between c++ and golang in synced performance from some aspects.C++ atomic library and mutex library can satisfy asynchronous requests.But I found difference through the realization of https://github.com/casbin/casbin/blob/master/enforcer_synced.go.C++ has no standard library for timer operations to notify  LoadPolicy.This means that a timing operation should be implemented through the chrono library.I need some suggestions and directions.

**Comment by bokket** [comment]
I try to analyze the difference between c++ and golang in terms of synchronization operations from some aspects.C++ atomic library and mutex library can satisfy asynchronous requests.But I found difference through the realization of https://github.com/casbin/casbin/blob/master/enforcer_synced.go. C++ has no standard library for timer operations to notify LoadPolicy.This means that timing operations should be implemented through the chrono library.I need some suggestions and directions.

**Comment by hsluoyz** [comment]
@divy9881

**Comment by EmperorYP7** [comment]
@bokket Hey there! I am analysing it as well and working on it. I would also like to add to your observations or rather promote the adaptation of RAII methodology for maintaining the states of mutex in current Cached Enforcer, if we ain't using atomic. ([which we should, by the way](https://stackoverflow.com/questions/15056237/which-is-more-efficient-basic-mutex-lock-or-atomic-integer))

If you're planning on implementing this issue, you may start with some code I've worked out for the `SyncedEnforcer`. https://github.com/EmperorYP7/casbin-cpp/blob/EmperorYP7/enforcer/casbin/enforcer_synced.h

Its far from perfect, but will save a _lot_ of time! (I hope)

**Comment by hsluoyz** [comment]
@xcaptain

**Comment by bokket** [comment]
Thank you @EmperorYP7 !Your work has inspired me a lot. If you want to improve performance or consider other aspects, atomic variables may be necessary. But now it is possible to use the RAII method to achieve multi-threading, at least it can prevent us from forgetting to unlock.
I now follow your ideas and refer to https://github.com/casbin/casbin/blob/master/enforcer_synced.go  and have completed most of the work.But the StartAutoLoadPolicy and SetWatcher inside are a bit problematic for me, because I just started contacting this project and did not fully understand its implementation principle.This is something  I have already accomplished. There are some details that need to be considered and thought about. I think it is worth. https://github.com/bokket/casbin-cpp/blob/master/casbin/enforcer_synced.cpp
I hope to have more advice and exchanges with you.Thank you.

**Comment by EmperorYP7** [comment]
@bokket Glad it helped you! :smile: I literally just added `atomic_bool` after my comment and forgot to push it. (we think alike, yay!) I have worked around it by making a custom ticker that utilises `std::async`, RAII mutexs' and atomic types with custom tick times and callback function which is called per tick. Here's the code:
https://github.com/EmperorYP7/casbin-cpp/blob/EmperorYP7/enforcer/casbin/util/ticker.h
https://github.com/EmperorYP7/casbin-cpp/blob/EmperorYP7/enforcer/casbin/util/ticker.cpp

Even this is not actually functional for the purpose. GoLang's abstraction for multithreading and especially for the `Ticker` is really good. We need to dig into this to get it working! But, this is quite a head start.

**Comment by EmperorYP7** [comment]
Hey, I think I managed to work around this, I still need to do some testing though. May I draft a PR for this? @bokket @hsluoyz

**Comment by bokket** [comment]
> 嘿，我想我设法解决了这个问题，不过我仍然需要做一些测试。我可以为此草拟公关吗？@bokket @hsluoyz

sure

**Comment by xcaptain** [comment]
Sorry for the late  reply, Actually I'm not quite understand why we need to add a `StartAutoLoadPolicy`, because now policies were already synced between database and memory, every update operation will update the database. Load policy from database to memory regularly seems not very necessary.

**Comment by EmperorYP7** [comment]
@xcaptain You mean the watcher will take care of it?

**Comment by xcaptain** [comment]
@EmperorYP7 Yes, currently `SyncedEnforcer` is thread safe using `mutex`, different threads share the same policies. This `StartAutoLoadPolicy` looks better in distributed scene, sync between between nodes. I suggest we close this issue and start a new issue discussing how to implement a watcher.
