### ISSUE TITLE
Use semantic-release to automatically release Casbin-CPP versions

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-cpp#39]
See: https://github.com/casbin/jcasbin/issues/76

**Comment by hsluoyz** [comment]
@divy9881 can you work on it?

**Comment by divy9881** [comment]
Yes, sure

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin-cpp/pull/44

**Comment by hsluoyz** [comment]
@divy9881 the link is wrong:

![image](https://user-images.githubusercontent.com/3787410/85353304-7a21fd80-b53a-11ea-9f25-9768520a5896.png)

**Comment by divy9881** [comment]
I have fixed it now.
