### ISSUE TITLE
Setup code coverage badge

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-cpp#41]
https://dev.azure.com/Casbin/casbin/_build/results?buildId=59&view=results

![image](https://user-images.githubusercontent.com/3787410/85221175-55b40d00-b3e4-11ea-92df-0131a83d2528.png)

https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops

**Comment by hsluoyz** [comment]
@divy9881 @zipochan can anyone do this?

**Comment by divy9881** [comment]
For now, the .coverage file format is not compatible to generate a code coverage statistics and badge. The file can only be viewed on VS enterprise edition.

**Comment by divy9881** [comment]
But, you can add coverage badge for .NET projects as it generates the code coverage in Cobertura format.

**Comment by divy9881** [comment]
For now, there is no solution for C/C++

**Comment by hsluoyz** [comment]
@divy9881 will using 3rd-party coverage tool like coveralls (https://github.com/casbin/casbin) work?

**Comment by divy9881** [comment]
No, not until we include travis-CI.

**Comment by hsluoyz** [comment]
@divy9881 in the option 1 you mentioned in: https://github.com/casbin/casbin-cpp/pull/37#issuecomment-647093475, we can also build on Travis-CI and then let Travis CI submit the coverage report to a coverage platform like coveralls. Can we do this?

**Comment by divy9881** [comment]
The coverage report is being prepared by using tests, our tests are in the form of MS Test, hence it may not prepare, as it does not support MSTest.

Maybe, we don't need coverage report for this particular project as can be seen from other C++ projects don't require, or if at all we require, after setup of cmake or makefile build, we can port our tests to GTest which is option 3.

**Comment by hsluoyz** [comment]
OK. Let's do other things first.

**Comment by EmperorYP7** [comment]
CTest can also be a really great option for testing. It is truly cross-platform, can be replicated on every OS and architectures and can be configured for consistent CI through GitHub Actions. Reference for GH Action for CTest: https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/.github/workflows/ci_workflow.yml

**Comment by hsluoyz** [comment]
@divy9881

**Comment by hsluoyz** [comment]
@EmperorYP7 does it support sending code coverage?

**Comment by hsluoyz** [comment]
@xcaptain

**Comment by EmperorYP7** [comment]
> @EmperorYP7 does it support sending code coverage?

@hsluoyz Yes, it does. And it's quite customizable.
https://github.com/pyarmak/cmake-gtest-coverage-example

**Comment by hsluoyz** [comment]
Then let's use it!

**Comment by hsluoyz** [comment]
@EmperorYP7 why two of these?

![image](https://user-images.githubusercontent.com/3787410/123788006-1630d280-d90e-11eb-9930-0f613f07b95e.png)

**Comment by EmperorYP7** [comment]
> @EmperorYP7 why two of these?
> 

v1.22.0 was released when #107 was merged. v1.24.0 released after merging #108 (just now) since both pointed to the same issue.

**Comment by EmperorYP7** [comment]
There'll also be another release when #109 will be merged to master. Should I change the releaser to update the release manually rather than updating it at each push?

**Comment by hsluoyz** [comment]
@EmperorYP7 well explained. Nothing needs to be done.
