### ISSUE TITLE
Setup benchmarks

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-cpp#42]
Really happy to see a new casbin product is born with good features, thanks @divy9881 for your hard work.

BTW, It's also interesting to see benchmarks numbers in casbin-cpp, normally cpp should win bench again rust and golang.

Could you add benchmarks?

**Comment by hsluoyz** [comment]
Sounds good. We can compare C++ with Rust.

**Comment by hsluoyz** [comment]
@divy9881 @zipochan

**Comment by EmperorYP7** [comment]
We may use custom benchmarking by making utility classes, or we may go for [Google’s benchmark tool](https://github.com/google/benchmark).

What kind of benchmarking is desired? Are we into visual benchmarking as well?

**Comment by hsluoyz** [comment]
@EmperorYP7 we want a cross-platform (Win, Linux, macOS), easy-to-use, modern and similar-to-Go benchmark solution, is there such a solution?

**Comment by EmperorYP7** [comment]
@hsluoyz I looked over the benchmarking implemented in casbin.
Google's benchmark would be perfect for this. It's cross-platform and quite similar to Go's benchmarking. May I take this up?

**Comment by hsluoyz** [comment]
OK!
