### ISSUE TITLE
Setup a code style linter

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-cpp#49]
I can usually find a lot of code style issues in our code like this PR: https://github.com/casbin/casbin-cpp/pull/48. I don't want to review and fix them one by one. We need a systematic and automatic way to solve it.

How does C/C++ solve the code linting issue? I want a solution better working for multiple OSes, multiple IDEs. I only know something like EditorConfig: https://editorconfig.org/

What tool does C/C++ project often use for code linter?

**Comment by hsluoyz** [comment]
Any suggestions? @xcaptain @nodece @GopherJ @divy9881 @zipochan

**Comment by xcaptain** [comment]
I think clang-format is good, maybe we can give it a try

**Comment by hsluoyz** [comment]
@xcaptain not bad!

**Comment by divy9881** [comment]
https://github.com/marketplace/actions/ros-style-guide-c-format
Its a github-action for automatic C++ code-formatter according to clang format

**Comment by divy9881** [comment]
some other github-actions:
https://github.com/marketplace/actions/c-code-linter-clang-tidy-and-cppcheck
https://github.com/marketplace/actions/c-c-code-linter-clang-tidy-clang-format-and-cppcheck

Let me know, which one, I will set it up.

**Comment by hsluoyz** [comment]
@xcaptain @divy9881 

I have several criteria: 

1. Works for all OSes: Windows, Linux, (better have macOS)
2. Works for IDEs: Jetbrains CLion, Visual Studio, (better have VSCode)

Which ones fulfill these?

**Comment by divy9881** [comment]
>I have several criteria:

>Works for all OSes: Windows, Linux, (better have macOS)
>Works for IDEs: Jetbrains CLion, Visual Studio, (better have VSCode)
>Which ones fulfill these?

Sorry, I didn't understand your question, the above links are the links to the github-actions, it gets triggered after all other build-tasks are successful and after may be merging.

**Comment by hsluoyz** [comment]
The linter I mean here is that when I type in code, the IDE will auto format my code. Usually IDE has its built-in linter or kind of similar things. But I want a standardized tool to work for all IDEs.

What does your linter mean?

**Comment by divy9881** [comment]
Then, I think we can set-up just git-hook for code linting using npm and clang-format as node-package.

**Comment by hsluoyz** [comment]
Will npm package work for CLion?

**Comment by divy9881** [comment]
> Will npm package work for CLion?

To setup a git-hook a contributor will have to install the npm packages from command line tool and after he adds the changed files to the staging area through `git add` the code formatting triggers automatically.

**Comment by hsluoyz** [comment]
Then I think maybe a tool like https://editorconfig.org/ is better. It's just a config file inside the repo (like Travis CI config). And the IDE can automatically recognize it and apply the code format checking.

**Comment by GopherJ** [comment]
IDE is not related to this repo I believe，developers need to use their own tool.

But we need some lint actions，ia there one for clang-format?  in vim I use clang，clang-format

code can  be formstted onced saved

This repo can also have custom style lint config? but it's normally not necessary

**Comment by ZipoChan** [comment]
Add the clangformat for Visual Studio.

**Comment by ZipoChan** [comment]
@hsluoyz  Have added clang-format,which can be used in visual studio.

**Comment by hsluoyz** [comment]
@ZipoChan which PR?

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin-cpp/issues/49
