### ISSUE TITLE
Integrate with envoy

### ISSUE THREAD

**Issue by xcaptain** [casbin/casbin-cpp#50]
Currently, envoy is using their own rbac module https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/rbac/v2/rbac.proto we can investigate if we can integrate envoy with casbin so envoy users can get more fine-grained access control

**Comment by divy9881** [comment]
I feel this issue must be open-sourced and we should wait for someone to take this up. The development of casbin-cpp library and its integration middleware applications must go in parallel for now.

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casbin/casbin-cpp/issues/115
