### ISSUE TITLE
cross platform compile casbin-cpp

### ISSUE THREAD

**Issue by xcaptain** [casbin/casbin-cpp#51]
Currently, casbin-cpp only builds on windows, we need to support linux and other os. Using CMake as the build system may be a solution

**Comment by divy9881** [comment]
I am working on it currently, for now, I want to complete the end-to-end testing of the entire project, after completing that, maybe after 10 days we can accomplish this.

**Comment by GopherJ** [comment]
cmake can generate compile_conmands.json，which also helps vim users

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin-cpp/pull/63
