### ISSUE TITLE
Integrate with mosquitto

### ISSUE THREAD

**Issue by bigcat26** [casbin/casbin-cpp#79]
Currently, I'm using mosquitto with it's own ACL module  [dynamic security plugin](https://mosquitto.org/documentation/dynamic-security/), but it was complex designed (such as groups & roles, priority id), and resource(topic) group was not supported.

If we can integrate mosquitto dynsec plugin with casbin, that would be great.

**Comment by hsluoyz** [comment]
@bigcat26 I think we can do it based on mosquitto team's response: https://github.com/eclipse/mosquitto/issues/2100

**Comment by bigcat26** [comment]
OK

**Comment by hsluoyz** [comment]
@EmperorYP7

**Comment by hsluoyz** [comment]
@bigcat26 why close?

**Comment by bigcat26** [comment]
> @bigcat26 why close?

Closing this issue as it has been inactive for a long time, and I am no longer working on it.

**Comment by gubertoli** [comment]
Hello! I am currently working on a Casbin plugin for Mosquitto v2.0+ that addresses this integration (and currently testing for my needs). 
The work in progress can be found here: [gubertoli/mosquitto-casbin](https://github.com/gubertoli/mosquitto-casbin)
Any feedback or further contributions are welcome.

**Comment by hsluoyz** [comment]
Hi @gubertoli great to see it! Do you mind creating a PR against: https://github.com/casbin/casbin-website-v2 to add this plugin to the official docs?

**Comment by hsluoyz** [comment]
PR created here: https://github.com/casbin/casbin-website-v2/pull/448
