### ISSUE TITLE
gcc complains "pragma once" in *.cpp file

### ISSUE THREAD

**Issue by bigcat26** [casbin/casbin-cpp#80]
gcc version
```shell
c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

compiler output:
```shell
[  1%] Building CXX object CMakeFiles/casbin.dir/casbin/enforcer.cpp.o
/usr/bin/c++    -g   -std=gnu++11 -o CMakeFiles/casbin.dir/casbin/enforcer.cpp.o -c /home/bigcat26/work/lab/third_party/casbin/casbin/enforcer.cpp
/home/bigcat26/work/lab/third_party/casbin/casbin/enforcer.cpp:17:9: warning: #pragma once in main file
   17 | #pragma once
      |         ^~~~
[  3%] Building CXX object CMakeFiles/casbin.dir/casbin/enforcer_cached.cpp.o
/usr/bin/c++    -g   -std=gnu++11 -o CMakeFiles/casbin.dir/casbin/enforcer_cached.cpp.o -c /home/bigcat26/work/lab/third_party/casbin/casbin/enforcer_cached.cpp
/home/bigcat26/work/lab/third_party/casbin/casbin/enforcer_cached.cpp:17:9: warning: #pragma once in main file
   17 | #pragma once
      |         ^~~~
[  5%] Building CXX object CMakeFiles/casbin.dir/casbin/internal_api.cpp.o
/usr/bin/c++    -g   -std=gnu++11 -o CMakeFiles/casbin.dir/casbin/internal_api.cpp.o -c /home/bigcat26/work/lab/third_party/casbin/casbin/internal_api.cpp
/home/bigcat26/work/lab/third_party/casbin/casbin/internal_api.cpp:17:9: warning: #pragma once in main file
   17 | #pragma once
      |         ^~~~
[  7%] Building CXX object CMakeFiles/casbin.dir/casbin/management_api.cpp.o
/usr/bin/c++    -g   -std=gnu++11 -o CMakeFiles/casbin.dir/casbin/management_api.cpp.o -c /home/bigcat26/work/lab/third_party/casbin/casbin/management_api.cpp
/home/bigcat26/work/lab/third_party/casbin/casbin/management_api.cpp:17:9: warning: #pragma once in main file
   17 | #pragma once
      |         ^~~~
[  8%] Building CXX object CMakeFiles/casbin.dir/casbin/model/function.cpp.o
/usr/bin/c++    -g   -std=gnu++11 -o CMakeFiles/casbin.dir/casbin/model/function.cpp.o -c /home/bigcat26/work/lab/third_party/casbin/casbin/model/function.cpp
/home/bigcat26/work/lab/third_party/casbin/casbin/model/function.cpp:17:9: warning: #pragma once in main file
   17 | #pragma once
      |         ^~~~
[ 10%] Building CXX object CMakeFiles/casbin.dir/casbin/rbac_api.cpp.o
/usr/bin/c++    -g   -std=gnu++11 -o CMakeFiles/casbin.dir/casbin/rbac_api.cpp.o -c /home/bigcat26/work/lab/third_party/casbin/casbin/rbac_api.cpp
/home/bigcat26/work/lab/third_party/casbin/casbin/rbac_api.cpp:17:9: warning: #pragma once in main file
   17 | #pragma once
      |         ^~~~
[ 12%] Building CXX object CMakeFiles/casbin.dir/casbin/rbac_api_with_domains.cpp.o
/usr/bin/c++    -g   -std=gnu++11 -o CMakeFiles/casbin.dir/casbin/rbac_api_with_domains.cpp.o -c /home/bigcat26/work/lab/third_party/casbin/casbin/rbac_api_with_domains.cpp
/home/bigcat26/work/lab/third_party/casbin/casbin/rbac_api_with_domains.cpp:17:9: warning: #pragma once in main file
   17 | #pragma once
      |         ^~~~
[ 14%] Building CXX object CMakeFiles/casbin.dir/casbin/util/built_in_functions.cpp.o
/usr/bin/c++    -g   -std=gnu++11 -o CMakeFiles/casbin.dir/casbin/util/built_in_functions.cpp.o -c /home/bigcat26/work/lab/third_party/casbin/casbin/util/built_in_functions.cpp
/home/bigcat26/work/lab/third_party/casbin/casbin/util/built_in_functions.cpp:17:9: warning: #pragma once in main file
   17 | #pragma once
      |         ^~~~
```

**Comment by hsluoyz** [comment]
@bigcat26 can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
got it, working on this

**Comment by bigcat26** [comment]
```bash
find . -name '*.cpp' |xargs sed -i -z -e  "s/#pragma once\n\n//"
# commit & push
```

**Comment by Zxilly** [comment]
@bigcat26 seems `#pragma once` was added deliberately
ref to: https://github.com/casbin/casbin-cpp/commit/18b41bc715f004b6dcbc840ed9391eb5a245953f and https://github.com/casbin/casbin-cpp/commit/52929cb0b908d90f65bf063295ca0df5c7347394
Warnings were explicitly ignored.

**Comment by bigcat26** [comment]
> @bigcat26 seems `#pragma once` was added deliberately
> ref to: [b69e3a3](https://github.com/casbin/casbin-cpp/commit/b69e3a3f5200572153a62c6fcb17523722217fdd), [18b41bc](https://github.com/casbin/casbin-cpp/commit/18b41bc715f004b6dcbc840ed9391eb5a245953f) and [52929cb](https://github.com/casbin/casbin-cpp/commit/52929cb0b908d90f65bf063295ca0df5c7347394)
> Warnings were explicitly ignored.
> Maybe prepared for some magic usage?


I love magic.
I just think replace '#ifdef/#define/#endif' with '#pragma once' in header files is reasonable..
[Pragma_once](https://en.wikipedia.org/wiki/Pragma_once)

**Comment by Zxilly** [comment]
@bigcat26 so just add `#pragma once` in `*.h`?
I think they can work together.

**Comment by divy9881** [comment]
MS VC++ requires `#pragma once` for its efficient execution on windows platform. We cannot do much about it. That's a trade-off we need to make while building the same code on linux. I have prepared 2 separate routines in CMake script to build the library.

**Comment by hsluoyz** [comment]
@divy9881 @bigcat26 can we wrap the `#pragma once` into a ifdef? Like:

```c
#ifdef WINDOWS_MSVC
#pragma once
#endif
```

**Comment by bigcat26** [comment]
1. In my knowledge, pragma once is a compiler directive, it just work at compile time, it is replacement of header guard macro.
2. MSVC compiler support "precompile header" help speed up compile progress.
3. Is there any document describes how "pragma once" optimize msvc program runtime speed?

**Comment by Zxilly** [comment]
@bigcat26 https://docs.microsoft.com/en-us/cpp/preprocessor/once?view=msvc-160

> We recommend the `#pragma once` directive for new code because it doesn't pollute the global namespace with a preprocessor symbol. It requires less typing, it's less distracting, and it can't cause symbol collisions. Symbol collisions are errors caused when different header files use the same preprocessor symbol as the guard value. It isn't part of the C++ Standard, but it's implemented portably by several common compilers.

**Comment by bigcat26** [comment]
> @bigcat26 https://docs.microsoft.com/en-us/cpp/preprocessor/once?view=msvc-160
> 
> 
> 
> > We recommend the `#pragma once` directive for new code because it doesn't pollute the global namespace with a preprocessor symbol. It requires less typing, it's less distracting, and it can't cause symbol collisions. Symbol collisions are errors caused when different header files use the same preprocessor symbol as the guard value. It isn't part of the C++ Standard, but it's implemented portably by several common compilers.


```
It has an effect similar to the include guard idiom, which uses preprocessor macro definitions to prevent multiple inclusions of the contents of the file. 
```

**Comment by EmperorYP7** [comment]
I don't think there is any noticeable performance difference between `#pagma once` and include-guards [SO discussion](https://stackoverflow.com/questions/1143936/pragma-once-vs-include-guards/34884735) on MSVC++. Include guards are more generic and won't throw warnings on compilation with Clang and GCC on MacOS and Linux (tested it myself). May I go ahead and create a PR for this?

**Comment by hsluoyz** [comment]
Good work!
