### ISSUE TITLE
Python bindings to facilitate PyCasbin-on-CPP

### ISSUE THREAD

**Issue by EmperorYP7** [casbin/casbin-cpp#84]
The project has the potential to utilize its C++ API for [PyCasbin-on-CPP](https://github.com/casbin/pycasbin-on-cpp) through Python bindings which will allow us to call C++ code from Python. CPython exposes various endpoints for us to make bindings, but this approach will be cumbersome and vulnerable to a lot of errors and memory leaks which won't be easy to debug. [pybind11](https://github.com/pybind/pybind11) can be used for making Python bindings and modules with C++11 as it is based on `Boost::Python` library.

**Comment by Zxilly** [comment]
Yes, this is our plan.
Before actually create the wrapper, we need to assure that casbin-cpp have all api of pycasbin.
Pycasbin on cpp will be regard as an optional high performance backend of pycasbin. But not a separate library.

**Comment by EmperorYP7** [comment]
@Zxilly I tried to make a boilerplate for the workflow to make these bindings and management of pybind11 module with CMake.
Here's the dev branch: https://github.com/EmperorYP7/casbin-cpp/tree/python-bindings kindly look at `./CMakeLists.txt` and `/ext/Findpybind11.cmake`

Is it somewhat similar to what you envisioned for this?

**Comment by EmperorYP7** [comment]
> Here's the dev branch: https://github.com/EmperorYP7/casbin-cpp/tree/python-bindings kindly look at ./CMakeLists.txt and /ext/Findpybind11.cmake

@hsluoyz @xcaptain is this approach feasible?

**Comment by Zxilly** [comment]
Good work.

**Comment by hsluoyz** [comment]
@EmperorYP7 I don't know the detailed Py-Cpp binding techniques, but we want:

1. Compatible across all OS: Windows, Linux, macOS
2. Simple, modern
3. Good performance

**Comment by EmperorYP7** [comment]
@hsluoyz yes, the bindings will be cross-platform. The performance will be similar to the resultant of `Boost.Python` library. It would be significantly more efficient than native Python performance.

**Comment by EmperorYP7** [comment]
> Good work.
> You can create a Pull Request for this.

Sure. But I think I should research it a bit more before diving in.

**Comment by hsluoyz** [comment]
@EmperorYP7 does pybind11 require CMake? I think we are not using CMake in this repo now? I remembered we are using .sln for Windows MSVC and makefile for Linux, the repo doesn't even build for macOS yet. How to resolve this?

**Comment by EmperorYP7** [comment]
> does pybind11 require CMake?

Not necessarily, but it's the best way to get it done.

> I think we are not using CMake in this repo now?

The project currently supports building the casbin library through CMake.

>  the repo doesn't even build for macOS yet

It does through CMake. But not reliably. 
<img width="1151" alt="Screenshot 2021-04-06 at 4 47 55 PM" src="https://user-images.githubusercontent.com/62606998/113703025-ebacf000-96f7-11eb-9df5-1bc96c09d47c.png">

@hsluoyz I am willing to work on an easy-to-maintain build system based on CMake. This would also include `.sln` and `.proj` files on building for Windows while also being compatible with Linux and macOS. Kindly see this file: https://github.com/EmperorYP7/casbin-cpp/blob/python-bindings/CMakeLists.txt

**Comment by hsluoyz** [comment]
lgtm!

**Comment by EmperorYP7** [comment]
> can you share what parts are still missing to make PyCasbin-on-CPP work?

I completely missed this one!
- Making pycasbin module `pip` installable instead of building it locally from the source.
- Benchmarking pycasbin's performance to compare it with Python's casbin implementation

**Comment by hsluoyz** [comment]
@EmperorYP7 great! Created two issues:

https://github.com/casbin/casbin-cpp/issues/180

https://github.com/casbin/casbin-cpp/issues/181
