### ISSUE TITLE
Improve portability

### ISSUE THREAD

**Issue by PDLdeLange** [casbin/casbin-cpp#88]
We love the effort but currently we can not use the project due to portability issues. I would propose to make the following changes.

- Introduce "casbin" namespace. 
- Remove "using namespace" in all headers.
- Remove "using std" everywhere. 

The latter two changes conflict with point 3 of the contribution guide which is actually considered bad practice and decreases portability. See: https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice.

Making these changes would make the project more inline with point 12 of the contributation guide and would improve portablity. See also: https://google.github.io/styleguide/cppguide.html#Namespaces.  

Happy to help out on this in case this issue is accepted.

**Comment by EmperorYP7** [comment]
> Introduce "casbin" namespace.

I agree. This is really something we should be incorporating here. 

> Remove "using namespace"/"using std" in all headers

Apart from that, the directory structure uses snake case which might create unnecessary conflicts with STL. Here's a [nice resource](https://youtu.be/4NYC-VU-svE?t=135) where I got to know about this first.

**Comment by hsluoyz** [comment]
@xcaptain

**Comment by bokket** [comment]
> > 引入"卡斯宾"命名空间。
> 
> 我同意。这确实是我们应该在这里纳入的东西。
> 
> > 删除所有标题中的"使用命名空间"/"使用 std"
> 
> 除此之外，目录结构的某些部分使用蛇壳，这可能会与 STL 产生不必要的冲突。这里有一[个很好的资源](https://youtu.be/4NYC-VU-svE?t=135)，在那里我首先了解了这一点。

Amazing! we are following the same YouTube blogger!

**Comment by xcaptain** [comment]
Agree, we should close https://github.com/casbin/casbin-cpp/issues/7 and can simply consider using google's style.

**Comment by hsluoyz** [comment]
@PDLdeLange I think your opinions sound good. Go ahead!

**Comment by PDLdeLange** [comment]
Okay!
