### ISSUE TITLE
Upgrade to C++17

### ISSUE THREAD

**Issue by EmperorYP7** [casbin/casbin-cpp#96]
The project can utilize the benefits of the modern C++17 standard. It is better, faster, and has more features than C++11. The features relevant for us include:

- [fold-expressions](https://en.cppreference.com/w/cpp/language/fold)
- [class template argument deduction (CTAD)](https://en.cppreference.com/w/cpp/language/class_template_argument_deduction)
- compile-time [`if constexpr`](https://en.cppreference.com/w/cpp/language/if)
- [inline variables](https://en.cppreference.com/w/cpp/language/inline)
- [structured bindings](https://en.cppreference.com/w/cpp/language/structured_binding)
- initializers for if and switch
- simplified [nested namespaces](https://en.cppreference.com/w/cpp/language/namespace)
- [lambda capture of *this](https://en.cppreference.com/w/cpp/language/lambda#Lambda_capture)
- new attributes:
     - [[[fallthrough]]](https://en.cppreference.com/w/cpp/language/attributes/fallthrough)
    - [[[nodiscard]]](https://en.cppreference.com/w/cpp/language/attributes/nodiscard)
    - [[[maybe_unused]]](https://en.cppreference.com/w/cpp/language/attributes/maybe_unused)
- [`__has_include ("filename")`](https://en.cppreference.com/w/cpp/preprocessor/include)

The above benefits would only compound with time and make this project up to date.

**Comment by hsluoyz** [comment]
@EmperorYP7 I think we should first build the community and the ecosystem around Casbin-CPP, because I'm afraid that currently there are no people using this repo.

I'm not saying optimizing our code is not important, but I think we should first do the pinned issues:

![image](https://user-images.githubusercontent.com/3787410/114726447-fc044100-9d6f-11eb-8d4f-7b1cb7544907.png)

**Comment by EmperorYP7** [comment]
@hsluoyz I agree with you. But integrating another project requires the completion of the current API to some extent, if not completely. Upgrading to C++17 can be thought of as an intermediary step towards that. I am thinking about the implementation of #79 and will soon come up with a solution.

**Comment by hsluoyz** [comment]
Will upgrading to latest C++ standard affect the integration with other projects like mosquitto? I think if their compiler toolchain is too old, then they will not support latest C++?

**Comment by EmperorYP7** [comment]
I don't think we would be injecting our source code directly into other projects, rather we'd be using libraries (binaries), and distribution-oriented code only. Mosquitto's codebase is mainly based on C, we'd have to create some kind of abstraction for it anyways. So I think this will not create any hindrance for integration.

**Comment by hsluoyz** [comment]
Good!
