### ISSUE TITLE
Cannot build Solution on Visual Studio 2019

### ISSUE THREAD

**Issue by hecma002** [casbin/casbin-cpp#97]
Hello everyone.
I am trying to build project with Visual Studio 2019. I follow the tutorial in your project with step:
- Clone project
- Double click on casbin.sln
- Click Build -> Build Solution

But compiler return some error with code C1083: cannot open include file. See picture
![image](https://user-images.githubusercontent.com/62142647/115667380-f90ce000-a36f-11eb-9203-9282687429ea.png)

I don't change any config in solution. I don't know where am I wrong. Can you help me solve my problem?
Many thanks.

**Comment by hsluoyz** [comment]
@EmperorYP7

/cc @divy9881

**Comment by EmperorYP7** [comment]
@hsluoyz On it! 🔨
